---
title: "Graph 1"
author: "Reynell Badillo Sarmiento" "Luis Trejos Rosero"
date: "2024-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r cars}
dismemberments <- read_csv("./Dismemberments_Barranquilla.csv")
```

## Graph 1 (Scales of Grey)

```{r}
#Add an indicator of competition or not
dismemberments <- dismemberments |> 
  mutate(competition = if_else(
    year == 2013 | year == 2016 | year == 2017 |
      year == 2021 | year == 2022, 1, 0
   )) |> 
  relocate(competition, .after = year)
```


## Graph 1 (Scales of greys)
```{r}
graph1_black_ <- ggplot(dismemberments, aes(x = `function`, fill = `function`)) +
  geom_bar(stat = "count") +
  labs(x = NULL, 
       y = "Number of Dismemberments",
       fill = "Function of the Dismemberment") +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.text = element_text(face = "bold", size = 11, margin = margin(t = 5, b = 5)),
    panel.spacing = unit(0.8, "lines")
  ) +
  scale_fill_grey(start = 0.1, end = 0.7) +
  facet_wrap(~competition, 
             labeller = as_labeller(c(`0` = "Criminal hegemony \n 2013-2015, 2018-2020",
                                      `1` = "Inter-criminal competition \n 2016-2017, 2021-2022")))

ggsave("dismemberment_graph_greys.pdf", plot = last_plot(), width = 7, height = 5)
ggsave("dismemberment_graph_greys.png", plot = last_plot(), width = 7, height = 5, dpi = 600)

```

## Graph 1 (colors)
```{r}
graph1_colors <- ggplot(dismemberments, aes(x = `function`, fill = `function`)) +
  geom_bar(stat = "count") +
  labs(x = NULL, 
       y = "Number of Dismemberments",
       fill = "Function of the Dismemberment") +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.title.x = element_blank(),
    strip.background = element_rect(fill = "gray90", color = NA),
    strip.text = element_text(face = "bold", size = 11, margin = margin(t = 5, b = 5)),
    panel.spacing = unit(0.8, "lines")
  ) +
    scale_fill_brewer(palette = "Greens") +
  facet_wrap(~competition, 
             labeller = as_labeller(c(`0` = "Criminal hegemony \n 2013-2015, 2018-2020",
                                      `1` = "Inter-criminal competition \n 2016-2017, 2021-2022")))

ggsave("dismemberment_graph_colors.pdf", plot = last_plot(), width = 7, height = 5)
ggsave("dismemberment_graph_colors.png", plot = last_plot(), width = 7, height = 5, dpi = 600)
```

